# .github/workflows/build-and-release.yml

name: Build Android APK and Release

# This workflow will run when a new tag matching 'release/*' is pushed.
on:
  push:
    tags:
      - 'release/*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest # Use a Linux runner for the build process
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for all tags and branches, which is needed for release actions
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x' # Or your preferred LTS Node.js version (e.g., '20.x')
          cache: 'npm' # Cache npm dependencies for faster builds

      - name: Install dependencies
        run: npm install --force # Use --force if you encounter peer dependency issues

      - name: Install EAS CLI
        # Ensure the absolute latest EAS CLI is installed to rule out versioning issues.
        run: npm install -g eas-cli@latest

      - name: Install JQ
        # jq is a lightweight and flexible command-line JSON processor, needed to parse EAS build output.
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Login to Expo (via environment variable)
        # EAS CLI automatically picks up EXPO_TOKEN from environment variables.
        # We use 'eas whoami' to verify successful authentication.
        run: eas whoami
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }} # Pass the token as an environment variable

      - name: Build Android APK with EAS (Cloud Build) and Get Build URL
        id: eas_build # Add an ID to reference this step's outputs
        # --json: Outputs build information in JSON format.
        # We pipe the output to jq to extract the `artifacts.buildUrl`.
        # The build URL is then set as a step output.
        run: |
          BUILD_JSON=$(eas build --platform android --profile production --non-interactive --json)
          BUILD_URL=$(echo "$BUILD_JSON" | jq -r '.[0].artifacts.buildUrl')
          if [ -z "$BUILD_URL" ]; then
            echo "Error: Could not extract build URL from EAS build output."
            echo "EAS Build Output:"
            echo "$BUILD_JSON"
            exit 1
          fi
          echo "build_url=$BUILD_URL" >> "$GITHUB_OUTPUT"
          echo "Extracted Build URL: $BUILD_URL"
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }} # Ensure EAS build also has access to the token

      - name: Download Built APK via URL
        # This step uses the build_url from the previous step's output to directly download the APK.
        run: |
          BUILD_URL="${{ steps.eas_build.outputs.build_url }}"
          if [ -z "$BUILD_URL" ]; then
            echo "Error: Build URL is empty. Cannot download APK."
            exit 1
          fi
          echo "Downloading APK from URL: $BUILD_URL"
          # Use curl to download the APK.
          # -L: Follow redirects.
          # -o app.apk: Save the downloaded file as app.apk.
          curl -L -o app.apk "$BUILD_URL"
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }} # Still good to have, though curl doesn't directly use it

      - name: Get tag name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release and Upload APK
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') # Ensure this only runs on tag pushes
        with:
          # Uses the current tag name as the release tag
          tag_name: ${{ steps.get_tag.outputs.TAG_NAME }}
          # Generates a release name based on the tag
          name: Release ${{ steps.get_tag.outputs.TAG_NAME }}
          # A brief description for the release. You can customize this.
          body: |
            ## New Android APK Release
            This release includes the latest Android application bundle.
            - Version: ${{ steps.get_tag.outputs.TAG_NAME }}
            - Built via GitHub Actions.
          draft: false # Set to true if you want to manually publish the release later
          prerelease: false # Set to true if this is a pre-release (e.g., alpha, beta)
          # Path to the APK file generated by EAS
          files: app.apk
        env:
          # GITHUB_TOKEN is automatically provided by GitHub Actions for authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
